## Workflow to show how to develop workflows in a branch

name: Develop in Branch
on: [pull_request, workflow_dispatch]
jobs:
    job1:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v4.1.0
            # - uses: devops-actions/actionlint@v0.1.1
            - run: echo "Hello ${{secrets.WHO_TO_GREET }} 👋 from ${{ github.actor }}"