## Workflow to show how to develop workflows in a branch

name: Develop in Branch
on: [pull_request, workflow_dispatch]
jobs:
    job1:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v4.1.5
            - uses: devops-actions/actionlint@c0ee017f8abef55d843a647cd737b87a1976eb69
            - run: echo "Hello ${{secrets.WHO_TO_GREET }} 👋 from ${{ github.actor }}"